// <auto-generated />
using System;
using MAVN.Service.AgentManagement.MsSqlRepositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MAVN.Service.AgentManagement.MsSqlRepositories.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191007145615_AddTokensRequirementsTable")]
    partial class AddTokensRequirementsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("agent_management")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MAVN.Service.AgentManagement.MsSqlRepositories.Entities.AgentEntity", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("customer_id");

                    b.Property<string>("SalesforceId")
                        .HasColumnName("salesforce_id")
                        .HasColumnType("varchar(100)");

                    b.Property<short>("Status")
                        .HasColumnName("status");

                    b.HasKey("CustomerId");

                    b.ToTable("agents");
                });

            modelBuilder.Entity("MAVN.Service.AgentManagement.MsSqlRepositories.Entities.ImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasColumnType("char(64)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnName("customer_id");

                    b.Property<short>("DocumentType")
                        .HasColumnName("document_type");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("images");
                });

            modelBuilder.Entity("MAVN.Service.AgentManagement.MsSqlRepositories.Entities.TokensRequirementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnName("amount");

                    b.HasKey("Id");

                    b.ToTable("tokens_requirement");
                });

            modelBuilder.Entity("MAVN.Service.AgentManagement.MsSqlRepositories.Entities.ImageEntity", b =>
                {
                    b.HasOne("MAVN.Service.AgentManagement.MsSqlRepositories.Entities.AgentEntity")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_images_agents")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
